Crowler/core/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from Crowler import db
from werkzeug.security import generate_password_hash,check_password_hash
from Crowler.models import User
from Crowler.core.spider import Spider
from Crowler.core.filtrs import User_Filtr
from Crowler.core.forms import FilterForm
from Crowler.users.forms import LoginForm

import requests
from bs4 import BeautifulSoup
import re

core = Blueprint('core', __name__)
offerts = []
length = ""

name = ""


@core.route('/', methods=['GET', 'POST'])
def index():

    global name

    form = LoginForm()

    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            #Log in the user

            login_user(user)
            flash('Logged in successfully.')

            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
            next = request.args.get('next')

            # So let's now check if that next exists, otherwise we'll go to
            # the welcome page.
            username = user.username
            name = user.username
            if next == None or not next[0]=='/':
                next = url_for('core.user_page', username = user.username)

            return redirect(next)
    return render_template('index.html', form=form)

@core.route('/<username>', methods=['GET', 'POST'])
def user_page(username):

    global offerts
    global length

    offerts = []
    length = []


    form = FilterForm()

    if form.validate_on_submit():

        user = User.query.filter_by(username=username).first_or_404()

        # make url and download olx page
        user_input = User_Filtr(form.number_of_rooms.data, form.price_from.data, form.price_to.data, form.localization.data)
        olxpage = user_input.make_taget_url()
        result = requests.get(olxpage)

        # if successful parse the download into a BeautifulSoup object, which allows easy manipulation 
        if result.status_code == 200:
            soup = BeautifulSoup(result.content, "html.parser")
    
        # find the object with HTML class wibitable sortable
        table = soup.find('table',{'class':'fixed offers breakword redesigned'})

        # loop through all the rows and get all informations 
        #offerts = []
        for row in table.find_all('tr', {'class':'wrap'}):
            img = row.find_all('img', {'class':'fleft'})
            title = row.find_all('a', {'class':'marginright5 link linkWithHash detailsLink'})
            price = row.find_all('p', {'class':'price'})

            link = [t.get('href') for t in title]
            # deal with errors
            if len(link) != 0:
                url = link[0]
                if "www.olx.pl/oferta" in url:
                    response = requests.get(url)
                    html = response.content.decode('utf-8')

                    offert_id = re.findall('(ID ogłoszenia: )(.*?)<', html)[0][1]
                else:
                    offert_id = '0'

            if offert_id not in user.viewed_flats_links:
                # order: img, title, link, price
                column = ([i.get('src') for i in img], [t.get_text() for t in title], [t.get('href') for t in title], [p.get_text() for p in price])
                offerts.append(column)

                user.viewed_flats_links += offert_id + ","
                db.session.add(user)
                db.session.commit()

        length = list(range(len(offerts)))
        

        

    return render_template('user_page.html',form=form, offerts=offerts, length=length)

@core.route('/delete_history')
def delete_history():

    global name
    print(name)

    user = User.query.filter_by(username=name).first_or_404()
    user.viewed_flats_links = ""
    db.session.add(user)
    db.session.commit()

    return redirect(url_for('core.user_page', username = user.username))

Crowler/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from Crowler import db
from werkzeug.security import generate_password_hash,check_password_hash
from Crowler.models import User
from Crowler.users.forms import RegistrationForm, LoginForm


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        user.viewed_flats_links = ''           
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('core.index'))
    return render_template('register.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))

Crowler/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Spider | Logowanie</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
    <form method="POST">
    {{ form.hidden_tag() }}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-32">
						Logowanie
					</span>

					<span class="txt1 p-b-11">
                        {{ form.email.label }}
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                        <!--<input class="input100" type="text" name="username" >-->
                        {{ form.email(class="input100") }}
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
                        {{ form.password.label }}
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
                        <!--<input class="input100" type="password" name="pass" >-->
                        {{ form.password(class="input100") }}
						<span class="focus-input100"></span>
                    </div>
                    <div class="flex-sb-m w-full p-b-48">
    
                            <div>
                                <a href="{{ url_for('users.register') }}" class="txt3">
                                    Zarejestruj się teraz »
                                </a>
                            </div>
                    </div>

					<div class="container-login100-form-btn">
						<!--<button class="login100-form-btn">-->
                            {{ form.submit(class="login100-form-btn") }}
						<!--</button>-->
                    </div>

				</form>
			</div>
		</div>
	</div>
    </form>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/js/main.js"></script>

</body>
</html>

Crowler/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Spider | Logowanie</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="static/css/util.css">
	<link rel="stylesheet" type="text/css" href="static/css/main.css">
<!--===============================================================================================-->
</head>
<body>
    <form method="POST">
    {{ form.hidden_tag() }}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-32">
						Rejestracja
					</span>

					<span class="txt1 p-b-11">
                        {{ form.email.label }}
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                        <!--<input class="input100" type="text" name="username" >-->
                        {{ form.email(class="input100") }}
						<span class="focus-input100"></span>
                    </div>
                    
                    <span class="txt1 p-b-11">
                            {{ form.username.label }}
                    </span>
                    <div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
                        <!--<input class="input100" type="text" name="username" >-->
                        {{ form.username(class="input100") }}
                        <span class="focus-input100"></span>
                    </div>
					
					<span class="txt1 p-b-11">
                        {{ form.password.label }}
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
                        <!--<input class="input100" type="password" name="pass" >-->
                        {{ form.password(class="input100") }}
						<span class="focus-input100"></span>
                    </div>

                    <span class="txt1 p-b-11">
                            {{ form.pass_confirm.label }}
                        </span>
                        <div class="wrap-input100 validate-input m-b-36" data-validate = "Password is required">
                            <span class="btn-show-pass">
                                <i class="fa fa-eye"></i>
                            </span>
                            <!--<input class="input100" type="password" name="pass" >-->
                            {{ form.pass_confirm(class="input100") }}
                            <span class="focus-input100"></span>
                        </div>


					<div class="container-login100-form-btn">
						<!--<button class="login100-form-btn">-->
                            {{ form.submit(class="login100-form-btn") }}
						<!--</button>-->
                    </div>

				</form>
			</div>
		</div>
	</div>
    </form>

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/bootstrap/js/popper.js"></script>
	<script src="static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/daterangepicker/moment.min.js"></script>
	<script src="static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="static/js/main.js"></script>

</body>
</html>

Crowler/templates/user_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spider | Mieszkania</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <ul class="nav justify-content-end">
        
        <li class="nav-item">
            <a href="{{ url_for('users.logout') }}" class="btn btn-dark">Wyloguj</a>
        </li>
    </ul>
    <div class="container">
    <div class="card">
    <div class="card-header">
    <form method="POST">
        {{ form.hidden_tag() }}<br>
        <div class="row">
            <div class="col">
                {{ form.number_of_rooms.label}} {{ form.number_of_rooms(class="form-control") }}
            </div>
            <div class="col">
                {{ form.localization.label }} {{ form.localization(class="form-control")}}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{ form.price_from.label }} {{ form.price_from(class="form-control")}}
            </div>
            <div class="col">
                {{ form.price_to.label }} {{ form.price_to(class="form-control") }}
            </div>
        </div><br>
        <div class="row">
            <div class="col"><a href="{{ url_for('core.delete_history') }}" class="btn btn-dark">Usuń historię wyszukiwań</a></div>

            <div class="col">{{ form.submit(class="btn btn-dark")}}</div>
        </div>            
        </div>
    </form>

    <div class="card-body">
    <ul class="list-group list-group-flush">
    {% for num in length %}
    <li class="list-group-item">
        <div class="row">
            <div class="col-4"><img src={{offerts[num][0][0]}} class="img-rounded" height="150" width="200"></div>
            <div class="col-6"><a href="{{offerts[num][2][0]}}">{{offerts[num][1][0]}}</a></div>
            <div class="col-2"><p>{{offerts[num][3][0]}}</p></div>
        </div>
    </li>
    {% endfor %}
    </ul>
    </div>
    </div>
    </div>

</body>
</html>